name: arguman

volumes:
  postgres_data:
  # pgadmin_data:
  mongo_data:
  redis_data:

services:
  # redis:
  #   image: redis:7.4.5
  #   volumes:
  #     - redis_data:/data/:Z
  #   healthcheck:
  #     test: redis-cli ping
  #     interval: 2s
  #     timeout: 3s
  #     retries: 40

  mongodb:
    image: code.edsd.net:5000/ideas-incubator/arguman/mongo:8.0.11
    build:
      context: .
      dockerfile: .docker/mongo/Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: arguman
      MONGO_INITDB_ROOT_PASSWORD: arguman
    volumes:
      - mongo_data:/data/db/:Z
      - mongo_data:/data/configdb/:Z
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 2s
      timeout: 3s
      retries: 40

  db:
    image: code.edsd.net:5000/ideas-incubator/arguman/postgres:17.5
    build:
      context: .
      dockerfile: .docker/postgres/Dockerfile
    environment:
      - POSTGRES_DB=arguman
      - POSTGRES_USER=arguman
      - POSTGRES_PASSWORD=arguman
    volumes:
      - postgres_data:/var/lib/postgresql/data/:Z
    healthcheck:
      test: pg_isready -U arguman
      interval: 2s
      timeout: 3s
      retries: 40

  # pgadmin:
  #   image: dpage/pgadmin4:9.5
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: dev@arguman.org
  #     PGADMIN_DEFAULT_PASSWORD: arguman
  #     PGADMIN_LISTEN_PORT: 80
  #   ports:
  #     - 127.0.0.1:15432:80
  #   volumes:
  #     - pgadmin_data:/var/lib/pgadmin/:Z
  #   restart: unless-stopped
  #   depends_on:
  #     - db

  web:
    image: code.edsd.net:5000/ideas-incubator/arguman/arguman:1.0.0
    build: .
    environment:
      - BASE_DOMAIN=localhost
      - POSTGRES_HOST=db
      - POSTGRES_USER=arguman
      - POSTGRES_PASSWORD=arguman
      - MONGODB_HOST=mongodb
      - MONGODB_USERNAME=arguman
      - MONGODB_PASSWORD=arguman
    ports:
      - "80:8000"
    depends_on:
      db:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      # redis:
      #   condition: service_healthy
