# Generated by Django 5.2.4 on 2025-07-14 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('language', models.CharField(max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('text', 'language')},
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('noun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='nouns.noun')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('is_featured', models.BooleanField(default=False, max_length=255)),
                ('nouns', models.ManyToManyField(blank=True, to='nouns.noun')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('hypernym', 'is a'), ('holonym', 'part of'), ('antonym', 'opposite with')], max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_relations', to='nouns.noun')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_relations', to='nouns.noun')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
