# Generated by Django 5.2.4 on 2025-07-14 07:42

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nouns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(help_text='\nThe main contention. It will be arguable with own premises. The Premises can prove or rebuttal this contention.<br> Examples: <ul> <li>Real art is for society, not for profit</li> <li>The meaning of life is 42</li> <li>Ethics man did what had to be done</li> </ul>', max_length=255, verbose_name='Argument')),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('owner', models.CharField(blank=True, help_text='\nThe owner of argument. It can be instutation, person, book, or a paper. Examples: <ul> <li>On the Origin of Species</li> <li>Friedrich Nietzsche</li> <li>Piet Mondiran</li> <li>The Guardian</li> </ul>', max_length=255, null=True, verbose_name='Original Discourse')),
                ('sources', models.TextField(blank=True, help_text='\nThe source of argument. It can be a URL, a book, or a newspaper. It is important for reliability of main contention.\n', null=True, verbose_name='Sources')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(choices=[('tr', 'Turkish'), ('en', 'English'), ('ch', 'Chinese'), ('es', 'Spanish'), ('fr', 'French'), ('pl', 'Polish')], max_length=5, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('nouns', models.ManyToManyField(blank=True, related_name='contentions', to='nouns.noun')),
                ('related_nouns', models.ManyToManyField(blank=True, related_name='contentions_related', to='nouns.noun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Premise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('premise_type', models.IntegerField(choices=[(0, 'but'), (1, 'because'), (2, 'however')], default=1, help_text='\n\nThe type of premise. It can be: <ul> <li> but: An objection against the contention. </li> <li> because: A reason for proof the contention. </li> <li> however: An additional situation for the premise. </li> </ul>', verbose_name='Premise Type')),
                ('text', models.TextField(blank=True, help_text='\nExample: We define happiness as a state of well-being, starting with being alive instead of dead.', null=True, validators=[django.core.validators.MaxLengthValidator(300)], verbose_name='Premise Content')),
                ('sources', models.TextField(blank=True, help_text="\nExample: Charles Darwin's The Origin of Species", null=True, verbose_name='Sources')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Published')),
                ('collapsed', models.BooleanField(default=False)),
                ('sibling_count', models.IntegerField(default=1)),
                ('child_count', models.IntegerField(default=1)),
                ('max_sibling_count', models.IntegerField(default=1)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.IntegerField(default=0)),
                ('argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premises', to='premises.contention')),
                ('parent', models.ForeignKey(blank=True, help_text="The parent of premise. If you don't choose anything, it will be a main premise.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='premises.premise', verbose_name='Parent')),
                ('related_argument', models.ForeignKey(blank=True, help_text='You can also associate your premise with an argument.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_premises', to='premises.contention', verbose_name='Related Argument')),
                ('supporters', models.ManyToManyField(related_name='supporting', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_premises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Please explain that why the premise is a fallacy.', null=True, verbose_name='Reason')),
                ('fallacy_type', models.CharField(choices=[('BeggingTheQuestion,', 'Begging The Question'), ('IrrelevantConclusion', 'Irrelevant Conclusion'), ('FallacyOfIrrelevantPurpose', 'Fallacy Of Irrelevant Purpose'), ('FallacyOfRedHerring', 'Fallacy Of Red Herring'), ('ArgumentAgainstTheMan', 'Argument Against TheMan'), ('PoisoningTheWell', 'Poisoning The Well'), ('FallacyOfTheBeard', 'Fallacy Of The Beard'), ('FallacyOfSlipperySlope', 'Fallacy Of Slippery Slope'), ('FallacyOfFalseCause', 'Fallacy Of False Cause'), ('FallacyOfPreviousThis', 'Fallacy Of Previous This'), ('JointEffect', 'Joint Effect'), ('WrongDirection', 'Wrong Direction'), ('FalseAnalogy', 'False Analogy'), ('SlothfulInduction', 'Slothful Induction'), ('AppealToBelief', 'Appeal To Belief'), ('PragmaticFallacy', 'Pragmatic Fallacy'), ('FallacyOfIsToOught', 'Fallacy Of Is To Ought'), ('ArgumentFromForce', 'Argument From Force'), ('ArgumentToPity', 'Argument To Pity'), ('PrejudicialLanguage', 'Prejudicial Language'), ('FallacyOfSpecialPleading', 'Fallacy Of Special Pleading'), ('AppealToAuthority', 'Appeal To Authority')], default='Wrong Direction', help_text='\nYou have to choose a fallacy type. For more information, you can look at the <a href="https://en.wikipedia.org/wiki/List_of_fallacies">wikipedia entry</a> for fallacies.', max_length=255, null=True, verbose_name='Fallacy Type')),
                ('contention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='premises.contention')),
                ('premise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='premises.premise')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
